version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: strapi-mysql-yt2
    restart: unless-stopped
    ports:
      - "1001:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi_db_yt
    volumes:
      - mysql_data:/var/lib/mysql
    
  strapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: strapi-cms-yt2
    ports:
      - "1337:1337"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  mysql_data:
  
  